apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.anfisa.name }}
  labels:
    app: {{ .Values.anfisa.name }}
    chart: anfisa
  annotations:
      argocd.argoproj.io/sync-options: Validate=false
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.anfisa.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.anfisa.name }}
    spec:

      securityContext:
        enabled: true
        fsGroup: 1000
        runAsUser: 0

      containers:
        - name: {{ .Values.anfisa.name }}
          env:
            - name: ANFISA_COORD_HOST
              value: druid-coordinator
            - name: ANFISA_ROUTER_HOST
              value: druid-router
            - name: ANFISA_MONGO_HOST
              value: druid-mongodb

          image: "{{ .Values.anfisa.output_registry }}/{{ .Values.anfisa.project }}/{{ .Values.anfisa.name }}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          stdin: true
#          command:
#            - "entrypoint"
#          args:
#            - "/usr/bin/entrypoint.sh"
          serviceAccount: default
          volumeMounts:
          - name: {{ .Values.anfisa.anfisa_volumes.data_volume }}
            mountPath: /data/
          - name: {{ .Values.anfisa.anfisa_volumes.workdir_volume }}
            mountPath: /anfisa/a-setup/

            ports:
              - name: http
                containerPort: 80
                protocol: TCP       
      volumes:
      - name: {{ .Values.anfisa.anfisa_volumes.data_volume }}
        persistentVolumeClaim:
          claimName: {{ .Values.anfisa.anfisa_volumes.data_claim_name }}
      - name: {{ .Values.anfisa.anfisa_volumes.workdir_volume }}
        persistentVolumeClaim:
          claimName: {{ .Values.anfisa.anfisa_volumes.workdir_claim_name }}

      terminationGracePeriodSeconds: 5
